### ISSUE TITLE
Do not change order of disposables

### ISSUE THREAD

**Issue by bobatsar** [hoc081098/disposebag#2]
In the code I have seen, that sinks are closed first and afterwards the subscriptions.

In my use case, the subscriptions handle some data and write into the sinks. As the dispose is async, it can happen, that the sinks are already closed, but the subscription are still active and try to write to the already closed sinks.

Why are the sinks closed first?
Shouldn't it be possible to close the resources in the order they were defined?

**Comment by hoc081098** [comment]
Sorry for late reply. I also ran into the same problem. Fixed release will coming soon
